package ch.hsr.adit.model;
// Generated 23.03.2017 08:47:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
public class Permission implements DbEntity {

	private int id;
	private String name;
	private Set roles = new HashSet(0);

	public Permission() {
	}

	public Permission(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Permission(int id, String name, Set roles) {
		this.id = id;
		this.name = name;
		this.roles = roles;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "role_permission", schema = "public", joinColumns = {
			@JoinColumn(name = "permission_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
