package ch.hsr.adit.domain.model;
// Generated 23.03.2017 08:47:58 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Advertisement generated by hbm2java
 */
@Entity
@Table(name = "advertisement", schema = "public")
public class Advertisement implements DbEntity {

  private long id;
  private AdvertisementState advertisementState;
  private Category category;
  private User user;
  private String title;
  private String description;
  private int price;
  private Date created;
  private Date updated;
  private Set tags = new HashSet(0);
  private Set medias = new HashSet(0);
  private Set messages = new HashSet(0);

  public Advertisement() {}

  public Advertisement(long id, AdvertisementState advertisementState, Category category, User user,
      String title, String description, int price, Date created) {
    this.id = id;
    this.advertisementState = advertisementState;
    this.category = category;
    this.user = user;
    this.title = title;
    this.description = description;
    this.price = price;
    this.created = created;
  }

  public Advertisement(long id, AdvertisementState advertisementState, Category category, User user,
      String title, String description, int price, Date created, Date updated, Set tags, Set medias,
      Set messages) {
    this.id = id;
    this.advertisementState = advertisementState;
    this.category = category;
    this.user = user;
    this.title = title;
    this.description = description;
    this.price = price;
    this.created = created;
    this.updated = updated;
    this.tags = tags;
    this.medias = medias;
    this.messages = messages;
  }

  @Id

  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "advertisement_state_id", nullable = false)
  public AdvertisementState getAdvertisementState() {
    return this.advertisementState;
  }

  public void setAdvertisementState(AdvertisementState advertisementState) {
    this.advertisementState = advertisementState;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "category_id", nullable = false)
  public Category getCategory() {
    return this.category;
  }

  public void setCategory(Category category) {
    this.category = category;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  @Column(name = "title", nullable = false)
  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @Column(name = "description", nullable = false)
  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @Column(name = "price", nullable = false)
  public int getPrice() {
    return this.price;
  }

  public void setPrice(int price) {
    this.price = price;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "created", nullable = false, length = 29)
  public Date getCreated() {
    return this.created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "updated", length = 29)
  public Date getUpdated() {
    return this.updated;
  }

  public void setUpdated(Date updated) {
    this.updated = updated;
  }

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "advertisement_tag", schema = "public",
      joinColumns = {@JoinColumn(name = "advertisement_id", nullable = false, updatable = false)},
      inverseJoinColumns = {@JoinColumn(name = "tag_id", nullable = false, updatable = false)})
  public Set getTags() {
    return this.tags;
  }

  public void setTags(Set tags) {
    this.tags = tags;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "advertisement")
  public Set getMedias() {
    return this.medias;
  }

  public void setMedias(Set medias) {
    this.medias = medias;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "advertisement")
  public Set getMessages() {
    return this.messages;
  }

  public void setMessages(Set messages) {
    this.messages = messages;
  }

}
