package ch.hsr.adit.domain.model;
// Generated 23.03.2017 08:47:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdvertisementState generated by hbm2java
 */
@Entity
@Table(name = "advertisement_state", schema = "public")
public class AdvertisementState implements DbEntity {

  private long id;
  private String name;
  private Set advertisements = new HashSet(0);

  public AdvertisementState() {}

  public AdvertisementState(long id, String name) {
    this.id = id;
    this.name = name;
  }

  public AdvertisementState(long id, String name, Set advertisements) {
    this.id = id;
    this.name = name;
    this.advertisements = advertisements;
  }

  @Id

  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @Column(name = "name", nullable = false)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "advertisementState")
  public Set getAdvertisements() {
    return this.advertisements;
  }

  public void setAdvertisements(Set advertisements) {
    this.advertisements = advertisements;
  }

}
