package ch.hsr.adit.domain.model;
// Generated 23.03.2017 08:47:58 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", schema = "public")
public class Media implements DbEntity {

  private long id;
  private Advertisement advertisement;
  private String filename;
  private String description;
  private byte[] media;

  public Media() {}

  public Media(long id, Advertisement advertisement, String filename, byte[] media) {
    this.id = id;
    this.advertisement = advertisement;
    this.filename = filename;
    this.media = media;
  }

  public Media(long id, Advertisement advertisement, String filename, String description,
      byte[] media) {
    this.id = id;
    this.advertisement = advertisement;
    this.filename = filename;
    this.description = description;
    this.media = media;
  }

  @Id

  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "advertisement_id", nullable = false)
  public Advertisement getAdvertisement() {
    return this.advertisement;
  }

  public void setAdvertisement(Advertisement advertisement) {
    this.advertisement = advertisement;
  }

  @Column(name = "filename", nullable = false)
  public String getFilename() {
    return this.filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  @Column(name = "description")
  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @Column(name = "media", nullable = false)
  public byte[] getMedia() {
    return this.media;
  }

  public void setMedia(byte[] media) {
    this.media = media;
  }

}
