package ch.hsr.adit.domain.model;
// Generated 23.03.2017 08:47:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MessageState generated by hbm2java
 */
@Entity
@Table(name = "message_state", schema = "public")
public class MessageState implements DbEntity {

  private long id;
  private String name;
  private Set messages = new HashSet(0);

  public MessageState() {}

  public MessageState(long id, String name) {
    this.id = id;
    this.name = name;
  }

  public MessageState(long id, String name, Set messages) {
    this.id = id;
    this.name = name;
    this.messages = messages;
  }

  @Id

  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @Column(name = "name", nullable = false)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "messageState")
  public Set getMessages() {
    return this.messages;
  }

  public void setMessages(Set messages) {
    this.messages = messages;
  }

}
