package ch.hsr.adit.domain.model;
// Generated 23.03.2017 08:47:58 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "public")
public class Role implements DbEntity {

  private long id;
  private String name;
  private Set users = new HashSet(0);
  private Set permissions = new HashSet(0);

  public Role() {}

  public Role(long id, String name) {
    this.id = id;
    this.name = name;
  }

  public Role(long id, String name, Set users, Set permissions) {
    this.id = id;
    this.name = name;
    this.users = users;
    this.permissions = permissions;
  }

  @Id

  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @Column(name = "name", nullable = false)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
  public Set getUsers() {
    return this.users;
  }

  public void setUsers(Set users) {
    this.users = users;
  }

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "role_permission", schema = "public",
      joinColumns = {@JoinColumn(name = "role_id", nullable = false, updatable = false)},
      inverseJoinColumns = {
          @JoinColumn(name = "permission_id", nullable = false, updatable = false)})
  public Set getPermissions() {
    return this.permissions;
  }

  public void setPermissions(Set permissions) {
    this.permissions = permissions;
  }

}
