package ch.hsr.adit.domain.model;
// Generated 23.03.2017 11:05:29 by Hibernate Tools 5.2.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "subscription", schema = "public")
public class Subscription implements DbEntity {
  
  private static final long serialVersionUID = 1L;

  private long id;
  private Category category;
  private User user;
  private long interval;
  private Date lastUpdated;

  public Subscription() {}

  public Subscription(long id, Category category, User user, long interval, Date lastUpdated) {
    this.id = id;
    this.category = category;
    this.user = user;
    this.interval = interval;
    this.lastUpdated = lastUpdated;
  }

  @Id
  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "category_id", nullable = false)
  public Category getCategory() {
    return this.category;
  }

  public void setCategory(Category category) {
    this.category = category;
  }

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "user_id", nullable = false)
  public User getUser() {
    return this.user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Column(name = "interval", nullable = false)
  public long getInterval() {
    return this.interval;
  }

  public void setInterval(long interval) {
    this.interval = interval;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_updated", nullable = false, length = 29)
  public Date getLastUpdated() {
    return this.lastUpdated;
  }

  public void setLastUpdated(Date lastUpdated) {
    this.lastUpdated = lastUpdated;
  }



}


